<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
	<PropertyGroup>
		<SpaRoot>..\..\frontend</SpaRoot>
	</PropertyGroup>
	<!--<Target Name="DebugFrontend" BeforeTargets="Build">
		<Exec Command="npm install" WorkingDirectory="$(SpaRoot)" />
	</Target>-->
	<!--<Target Name="DebugFrontend" BeforeTargets="Build">
		<Exec Command="npm run dev" WorkingDirectory="$(SpaRoot)" />
	</Target>-->
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
  </ItemGroup>	

</Project>
