// <auto-generated />
using System;
using KeepApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace KeepApi.Data.Migrations
{
    [DbContext(typeof(KeepDbContext))]
    partial class KeepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeepApi.Data.Entity.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(32)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ArchievedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Archived")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ARCHIVED");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(30)")
                        .HasDefaultValue("default")
                        .HasColumnName("COLOR");

                    b.Property<string>("Content")
                        .HasColumnType("NCLOB")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool>("Pinned")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PINNED");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ReminderAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REMINDER_AT");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("NOTES", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
